### PR TITLE
Fix closing tag typos

### PR DESCRIPTION
**Pull request by cmbuckley**
Fix a number of typos with closing tags, e.g. `</ strong>` → `</strong>`.

### CODE REVIEW

**Comment by cmbuckley** [comment]
Rebased off current master. @mattl tagging if you're interested in this

**Comment by mattl** [comment]
@cmbuckley Thanks. But these translations are generated via Transifex. I'll loop @RCEurope1 in and hope they can pass these fixes along to our translation team

**Comment by RCEurope1** [comment]
Hi, please elaborate a little more what this is about. Happy to relay stuff or fix it, but need to understand first ...

**Comment by cmbuckley** [comment]
Hi, hopefully fairly straightforward:

A number of closing tags in the translations contain an errant space (e.g. `</ strong>` instead of `</strong>`). This results in invalid HTML appearing in the licenses.

For example, note how the malformed `</ strong>` on [cc/i18n/po/es/cc_org.po:2920](https://github.com/creativecommons/i18n/blob/cc6360a70efae77372b9bbef579293621b96ebb4/cc/i18n/po/es/cc_org.po#L2920) results in invalid HTML on http://creativecommons.org/licenses/by-nd/3.0/cl/, causing the `<strong>` tag around **Compartir** to never be closed, and thus rendering the rest of the page in bold. (You can also see other issues on this page from malformed `</ a>` tags.)

**Comment by aldenstpage** [comment]
It looks like this was due to a typo in a `cc.engine` template, which was fixed some time ago. We can't accept modifications to the Transifex files because those are pulled from an online web service; formatting issues have to be fixed inside of the templates.

**Pull request closed without merging**
